# Makefile

JAR_NAME = /Users/dgodstand/java/pomodoro-focus-timer/pomodoro-timer/target/pomodoro-timer-0.0.1-SNAPSHOT.jar

build:
	@mvn clean package

run:
	@java -jar $(JAR_NAME)

clean:
	@mvn clean
